export const guests = [
    {
        "name": "Mr Yan Pomplemeyer",
        "bio.1": "Our guest liar for July and August 1995 was",
        "bio.2": "Mr Yan Pomplemeyer",
        "bio.3": "of The Liebfraumilch Institute of Tomato Science, Frankfurt, Germany.",
        "bio.4": "Mr Pomplemeyer's chosen topic was Extraterrestrial Space Aliens.",
        "lies": [
            "The Sears tower in Chicago was built by aliens.",
            "Giraffes are a direct result of a cross-breeding programme between a race of particularly tall alien space beings and our human ancestors.",
            "The Egyptian pyramids were in fact built by the pharohs in an attempt to reach the stars. Unfortunately, despite ever greater achievments, their pyramids could not generate enough lift to escape the gravitational pull of the Earth. ",
            "Alien beings have signed an exclusive five album deal with Mark Knopfler's Dire Straits. The band have also agreed to stage the opening night of their forthcoming world tour on the alien home planet, 28 million light-years from Earth.",
            "US President Abraham Lincoln was named after the famous brand of motor-car, the Ford Lincoln. "
        ]
    },
    {
        "name": "Mr Rob Smith",
        "bio.1": "Our guest liar for September and October 1995 was",
        "bio.2": "Mr Rob Smith",
        "bio.3": "of the University of Newcastle Upon Tyne, England.",
        "bio.4": "Mr Smith's chosen topic was Hollywood Celebrities.",
        "lies": [
            "Many people are aware that magpies often steal glittery objects, and other such trinkets with which to line their nests.  Not so many people know that they also do a roaring trade in these objects to the jackdaws who lack both the insight and the bottle to orchestrate such thefts themselves.",
            "Prior to drinking the contents of a newly opened carton of milk or orange juice, it is usually advisable to riddle the carton with bullets from a high-velocity rifle.",
            "Badgers are very much more intelligent than many people might suppose.  Many of them have elaborate underground cities, complete with cinemas, theatres and hook-a-duck stalls.",
            "Many people appreciate the fact that elephants cannot jump, but it is not widely known that the reason for this is that they are just too damn stupid.",
            "Contrary to popular belief, empty cardboard boxes are in no way suitable for putting things in.",
            "Top London hairdressers are now starting to remove each hair individually, cut it in half, and then sew it back into the scalp.",
            "Scientists have recently revealed that the cavepeople of the northern hemisphere did not in fact live in caves, but instead made nests constructed entirely from small pieces of coal and chewed-up second-rate paperback detective novels.",
            "Lemurs make ideal replacements for missing Monopoly&copy; pieces.",
            "Recent legislation in the United States has prohibhited the use of comedy glasses which consist of ordinary spectacle frames with fake eyes protruding on large springs."
        ]
    },

    {
        "name": "Mr Frank Charlton",
        "bio.1": "Our third guest liar was",
        "bio.2": "Mr Frank Charlton",
        "bio.3": "of Tachyon Communications.",
        "bio.4": "Mr Charlton's chosen topic was 17th Century Agricultural Practices.",
        "lies": [
            "The energy generated by a pair of mice engaged in sexual intercourse is sufficient to power Vice Prime Minister Michael Heseltines Electric Techno-Underpants for one year.",
            "The common Goldfish is a voracious predator. A United Nations ruling in 1941 stated that henceforth all such piscines must be confined within small transparent bowls constructed from the residue left by melting Edith Piaf records.",
            "The videogame character \"Mario\" was invented when a Nintendo executive observed Labour MP Ken Livingstone stomping on mushrooms in a frenzy during his addiction to Lemsip.",
            "The Internet is housed in the cassette deck of a Commodore VIC-20, located on the small Scottish Island of Ballyhoo.",
            "The ritual of circumcision actually renders a man invisible to attacking bushbabies.",
            "The record \"There's no-one quite like Grandma\" by St. Winifred's School Choir is known to contain back-masked messages, including \"Hamsters are the tools of Beelzebub\".",
            "Dialling a random seven-digit number beginning with 5 will always connect you to a man named Smegma.",
            "The perfume now known as \"Obsession\" was previously marketed as a man's aftershave called \"Midnight In A Weightlifter's Jockstrap\", by Algonquin Swivel.",
            "Kellog's Pop Tarts © are the leftovers from a Chemical Warfare plan abandoned by the Chinese Government in 1886.",
            "\"Supermarket Sweep\" star Dale Winton has stored all of his bodily effluent in small labelled fish-paste jars since the age of seven.",
            "Wearing nylon underpants screen-printed with a colourful picture of Alan Titchmarsh is required by law in Milton Keynes.",
            "Reclusive inventor Howard Hughes' final invention was the little-known Magnetic Cleft-Fluff Remover.",
            "Custard is extracted from a tiny gland in a South African bird known as the Knibble.",
            "Shrubbery is illegal in some states of the USA.",
            "The entire Welsh village of Knobbler was removed from maps in 1965, in an attempt by the Government to cover up the secret landing of Space Cockatoos from beyond the Galactic Rim.",
            "String is too short.",
            "Underpants are punishable by death in some parts of the Australian outback.",
            "Canada is manufactured entirely from shoeboxes rejected by Fit-Rite."
        ]
    },

    {
        "name": "Sir Greg O'Beirne",
        "bio.1": "Our guest liar for January '96 was",
        "bio.2": "Sir Greg O'Beirne",
        "bio.3": "from Australia.",        
        "lies": [
            "The Harmonica was invented by Sir Charles Scrotum, who despised beggars whistling on street corners.",
            "Mountain Goats is a hobby practiced by sex-starved Albanians.",
            "Superglue was originally developed for use as a hairspray, but was quickly abandoned when it was realised that one application fixed a hairstyle for 35 years, and was therefore deemed \"unfashionable\".  It is now only used by old-age pensioners.",
            "Early vacuum cleaners consisted only of a broom with a drinking straw attached to the base, and needed two people to operate effectively.",
            "President Kennedy was not assasinated.  In fact, he suffered a rare hormonal condition which tended to cause his head to explode when travelling in open-top cars near grassy knolls.",
            "Pope John Paul II was formerly the lead singer of a Polish death-metal band."
        ]
    },

    {
        "name": "Mr. Jo(e/seph) Reeves",
        "bio.1": "Our fifth guest liar was",
        "bio.2": "Mr. Jo(e/seph) Reeves",
        "bio.3": "inventor of the electric toothbrush and the first man to set foot on Neptune.",
        "bio.4": "His chosen topic was shoe designs for people with no feet.",
        "lies": [
            "The earliest known example of government propaganda is the Bayeux Tapestry.  William \"The Conqueror\" actually won England from King Harold in a high stakes game of \"pissenlit\", an early forerunner of poker that was popular in France at the time.  After the game, Harold and William (who were still the best of friends) decided to produce the tapestry in order that William's newly acquired subjects should feel better about their new king, and also so that Harold's mother, who strongly disapproved of gambling (at least for anything larger than the Orkneys), would not attempt to find and chastise her errant son, believing him dead.  The Doomsday Book was instigated some years later by William, when he became suspicious that Harold - now living as a playboy in the French court - had taken some of England with him; and, indeed, upon the completion of the Book, it was discovered that thirty-two cows, fourteen chickens, eighty-seven virgin maidens, and three small villages were missing.  This - still unhonoured - gambling debt is the real root of the enmity between England and France that survives to this day. ",
            "The word \"viper\" was originally derived from the words \"biscuit\" and spongy.",
            "Sir Robert Peel is famous, not only for being the founder of Britain's police force, but also for being the first Scot to possess a navel since they were first banned in Scotland during the reign of Louis XIV. ",
            "If it wasn't for paper, we would all die.",
            "Morrissey's favourite party trick is to burp the whole of \"Girlfriend In A Coma\", pausing for breath only three times.  ",
            "The most common name in Africa is Blpp.",
            "The overwhelming majority of heart attacks are caused by a fatal combination of smiling while jogging.  The extra strain on the facial muscles is enough to push most people's cardiovascular systems just that little bit too hard.  This is why most joggers prefer to dribble and wobble their cheeks.  ",
            "In March 1973, during a routine stomach operation, the royal veterinary surgeon found the undigested bodies of three royal butlers inside one of the Queen's corgis.  The corgi was arrested when it was discovered that all three butlers had continued to use their Visa cards after their respective disappearances, and their banks revealed that they had bounced nearly twenty cheques that appeared to have been signed with paw-prints.  The corgi, whose anonymity has always been preserved for reasons of national security, died in Wandsworth jail in 1977, during a knife fight with another inmate over a high-stakes game of poker.",
            "Horse radish has only relatively recently been used as a condiment.  It was originally intended as a haemmorhoid cure.  ",
            "Modern typewriter keyboards were first designed by Mrs. Helen Rancid, an nineteenth-century innovator noted, among other things, for the fact that she had seventeen fingers.",
            "Most word processors will not print the word \"toop\" for religious reasons.  ",
            "Angels frequently descend to Earth in the guise of road maintenance workers.",
            "Japan was officially at war with the small Suffolk town of Brome for 174 years.  During the entire war, only seventeen shots were fired: in 1877, the Japanese ambassador to Britain fired twice at a London fruit-market trader whom he suspected (wrongly) of coming from Brome, missed, and was promptly deported; and in 1944, an American pilot, whose mother had emigrated from Brome to Los Angeles forty years previously, took particular relish in firing his first - and only - nine rounds at a Japanese aircraft carrier before he himself received six bullets to the head from a fanatically anti-Brome Japanese spy who had been hiding in the rear of the cockpit.  Peace broke out in 1983, when it was finally realised that there were no surviving records of the incident that had supposedly started the war, and that the whole thing was bloody stupid anyway. ",
            "In 1995, three men died of matricide.",
            "The letter \"w\" was originally intended as a joke.  Dr Samuel Johnson placed it liberally throughout his Dictionary in order to provide some light relief, and to amuse his friends.  Unfortunately the joke backfired horribly, as everyone, including his friends, took it absolutely seriously.  To this day, the letter still does not have a sensible name. It is said that Doctor Johnson died an angry man, and finally passed away screaming the words \"Weasles! Wensleydale! Wishy-washy! Work! Wimbledon, tupperware, twenty-two, twins!\" to anyone that could hear him.  In his will, he requested that none of his descendents should ever be called William, Wallace, Wilbur, Wilma, or (mysteriously) Edgar. "
        ]
    },

    {
        "name": "Dr. Steve Greatbanks",
        "bio.1": "Our sixth guest liar was",
        "bio.2": "Dr. Steve Greatbanks",
        "bio.3": "who first achieved fame playing the role of <br/>James Bond in \"Diamonds are For Your Eyes Only\"",
        "bio.4": "Dr Greatbanks has since gone on to discover two lost<br/>continents,</br>three lost socks and the Holy Lost Pigeon of St. Jeremy.",
        "lies": [
            "The Pope finds that nothing is more effective in helping him to unwind at the end of a hard day than a spell as the hind legs of a pantomime cow.",
            "Under the terms of the Geneva convention, gherkins are classified as a nerve agent.",
            "Have you ever wondered about how heavy footballs used to look in old television reports? Well, the very 'ball' which was used in the 1928 F.A. Cup Final was re-discovered recently and found, upon scientific examination, to be a 37.5 Kg sphere of granite with a thin covering of Capybara leather. No wonder headed goals were so rare in those days!",
            "Elephants hibernate in straw-filled boxes under stairs.",
            "Simply including the &lt;LOTTOJACKPOT&gt; and  &lt;/LOTTOJACKPOT&gt; tags around any six numbers on a WWW page will make you rich beyond your wildest dreams.",
            "Tree frogs, though deceptively small, have voracious appetites and just one 50 gramme adult male can single-handedly eat over 45 hectares of rain forest in a single sitting.",
            "The Canadian Seal cull is secretly funded by Greenpeace.",
            "The eggplant is so named because of the unique ability of this amazing plant to reproduce in the same manner as the common chicken.",
            "Most common gardening accidents could be prevented by wearing sturdy corduroy trousers.",
            "Gino Ginelli ice cream was brought to Europe from China by Marco Polo.",
            "The 'soap-on-a-rope', now thought of as a mere item of bathroom kitsch, was originally used as an instrument of torture by the Spanish Inquisition.",
            "'Electronic' computers are not, in fact, powered by electricity. They are really powered by dozens of minature wooden water wheels.",
            "Many common skin complaints can be readily cured by the liberal application of a paste of Cheddar cheese, Dolphin dripping and artichokes.",
            "The Belgian Congo was named in remeberance of the tragic deaths of five generations of the van Sputum family, famous Brussels socialites, who hurtled (in a single chain) from a seventh floor window during a particularly riotous Embassy party in 1842. To this day, the Belgian constitution forbids both 'linked or chain dancing' and Agadoo singles (though Albums are strangely exempted).",
            "Former Cambodian despot Pol Pot is a member of Mensa.",
            "Before the invention of Gravity by Isaac Newton, it was quite possible, and even fashionable, to levitate small pieces of fruit in one's parlour.",
            "The bouncy castle, unknown in this country before 1974 has been popular in Tibet since 1693 after the then incumbent Dalai Lama exhorted it's use in the path to enlightenment.",
            "The Lebanese city Beirut (a corruption of the German, Bayreuth) was named by the aggrieved Friedrich Grondelholster who founded his own (rather unsuccesful) Wagner festival, predating the birth of the composer by some 40 years.",
        ]
    },

    {
        "name": "Mr Paul Craggs",
        "bio.1": "Welcome to the Liars Podium",
        "bio.2": "Mr Paul Craggs",
        "bio.3": "with his specialised subject<br/>`The Life and Times of Dudley Pagdet, budgerigar tamer ahead of his time'",
        "bio.4": "Mr Craggs tells us that his favourite food is any fat and that he works as a test driver for McLaren,</br>the pram and push-chair manufactures of world renown.",
        "lies": [
            "News of a massive Fraud connected with 'anonymous' National Lottery winners broke this week.A Mr Herbert George Wells and an accomplice as yet named only as 'Dr Who?' by a police insider, are being quizzed by detectives from the Serious Fraud Office and League Against Lottery Cheaters in 1927 and 2010 respectively.",
            "Oregano, the common herb on pizzas, is made from badgers and bits of Austin Sevens.",
            "Two thirds of people who bought 'Batman Forever' on video now suffer from epilepsy following the infamous `Ketchup' scene.",
            "98% of people questioned in a recent National survey believed Mao Tse Tung to be that dish you get with cashew nuts and an unidentifiable meat in it.",
            "Rugby League rules specifically exclude molluscs from play.",
            "The 1924 Vatican Ecumenical Sub-committee on Wombats, decreed that both cardboard milk cartons of the type manufactured by Tetra-Pac © and nail- scissors were miracles of biblical proportions. The same assembly ruled that Brylcreeme was the Devil's salad dressing.",
            "Terry Christian, infamous TV presenter and part-time shoelace tester has not had a bath since 5th February 1973, when he found a dead yak in the tub of his Mosley home, triggering in him a permanent psychosis of all water borne, humped, grunting oxen.",
            "\"Throwing the baby out with the bath water\" allegorical proverb or hard fact? An alarming recent study showed that 11% of families had done just that.",
            "All bush-babies have the Christian name Bertram.",
            "`A bird in the hand is worth two in the bush' is not so much a lie as an inaccuracy, currently a bird in the hand is actually worth a pig in poke.",
            "Honda cars all contain a small amount of lard concealed in the door-skins.",
            "The Spanish word `jerigonza' has no direct translation into English, the nearest meaning being `sweetly fluffy, with bits of string attached'.",
            "Rubber comes from cows.",
            "It is a common fallacy that a leopard can not change his spots. As long as he has the receipt and returns them unworn within fifteen days of purchase he is free to choose from a bewildering array of alternative patterns including diagonal flashes and paisley.",
            "Uffculme, Devon, is a pivotal point for World Cheese Policy."
        ]
    },

    {
        "name": "terry@noonien.demon.co.uk",
        "bio.1": "Essex Pig-Tattooist of the Year (1975)",
        "bio.2": "Champion Bee-hive Sculpturist of the Season (Butlin's, Filey, 1994)",
        "bio.3": "Emperor of Latvia (1929-)",
        "lies": [
            "Rubber thimbles were first patented by prolific writer Ernest Hemingway.",
            "The Texan city of Dallas took its name from a TV show popular in that state in the late 1970's.",
            "Pasteurised Milk is so called after it's inventor: Louis Milk.",
            "Soap on a rope is grown rather than manufactured. Seeds can be bought at any good horticultural outlet.",
            "The 8-track audio cartridge will have completely replaced the CD as the electro-magnetic recording medium of choice by late in 1998.",
            "It was only late in 1973 that the now-accepted standard order for the numerals 1 to 9 was adopted. The decision was made necessary by an unexpected boom in the counting industry.",
            "The `W' in `FW Woolworth & Co' stands for \"Dachshund\".",
            "Hong Kong Phooey is filmed before a live studio audience.",
            "The Arctic Circle is actually a perfect triangle.",
            "Before finally naming the \"Big Mac\", the McDonald brothers discarded several hundred alternatives, including the name \"Aunt May's Big Bap\" after their mother's sister, Maybelline Rothstein, who only had one breast.",
            "The common cow (bovis bovis) has been known to direct fellow cows to areas of fresh grass by performing a \"wiggling\" figure of eight dance, with the central line of the \"eight\" ponting towards the grass.",
            "The original title of Lennon & McCartney's \"I am the Walrus\" was \"I am the Wombat\". The title was changed following a short but intense period of walrus-culling by a team of Brazilian expatriots in Greenland. Songwriter Lennon wanted to draw public attention to the plight of the ugly but much misunderstood animals.",
            "The human nose contains over 350 separate bones.",
            "Helicopters to be filmed for television have four really wide rotor blades that rotate very slowly during flight.",
            "Skippy the Bush Kangaroo was actually a trained koala in a suit.",
            "The Domesday Book was originally published in twenty-four monthly parts, with part two being given away free with part one. A binder for easy storage is still available."
        ]
    },

    {
        "name": "Mr Ade Ward",
        "bio.1": "International Busby thrower, 1647 BC.",
        "bio.2": "Most Impressive Collector of Shiny Things, Ruislip Manor, 1992.",
        "bio.3": "Winner of the \"Mr Trowell Impersonator\" award, 1995.",
        "lies": [
            "You can obtain a UK passport by sending a stamped addressed envelope to 'Passport Competition, PO Box 66, London', answering the simple question \"What colour is the sky?\"",
            "When somebody is confused, their brain turns inside out and back to front. Therefore it is always important to speak backwards when people are confused.",
            "Michael Caine was born in 1742 in Paris. Only today's extensive plastic surgery and complex medication keep him alive.",
            "The famous cartoonist Gary Larson is in fact a large orange rectangular tube containing fourteen pounds of kerosene.",
            "Macromedia have released their latest Shockwave plug-in: \"Smellwave\" which provides aromatic media for the internet.",
            "The German for potato is \"Kartoffeln\" which directly translated means \"Carpet tape juice\".",
            "Contrary to popular belief, the famous disc jockey Mark Goodier is in fact a large inflatable rubber sack with a clever pump device to move air through a set of wooden vocal chords, which causes him to talk.",
            "The colour white is made up of 56% red, 32% green and 12% orangutan.",
            "In some eastern countries of the world, HTML is actually the spoken language.",
            "The popular music group \"Pet Shop Boys\" are made of cardboard and sticky back plastic.",
            "The common cough is caused by carpetness of the lungs.",
            "The name George derives from the Anglo Saxon name `Gorge' which mean `to fill your self silly with jelly and ice cream'. It's common use in today's society is only possible through special diodes which deliberately break.",
            "In mathematical terms, the word `floating point' means that the person carrying out the maths has forgotten where to put it.",
            "The common flea is manufactured by The Jet-Ram Company of Bristol, England.",
            "Light Emitting Diodes (LEDs for short) are infact small flies which have been caught inside a red (or green) plastic casing. When power is placed to the terminals of a LED, the fly inside gets frightened, and turns on a tiny torch to see if it can find a way out."
        ]
    },

    {
        "name": "Mr Dave Kenning",
        "bio.1": "Our tenth guest liar was",
        "bio.2": "Mr Dave Kenning",
        "bio.3": "an unemployed career consultant from Tierra del Fuego.",
        "lies": [
            "Zorba the Greek was, in fact, Swedish.",
            "Actress Andie Mac Dowell is banned under EC directive 16738/-3E (1983), restricting use of certain food colouring agents.",
            "Lemons are born purple but pygmy lemon-grove dwellers paint them yellow to please their wives.",
            "Sparrows are unable to fly. They cleverly mimic flight by hanging on to strings attached to albatrosses and flapping their otherwise useless wings.",
            "According to new research by nutritionists, the four major food groups are cheese, gin, chocolate and McVitie's Jaffa Cakes.",
            "The bubbles in champagne are painstakingly hand-painted by Trappist monks.",
            "TV super-chefs Gary Rhodes and Rick Stein are mortal enemies since an incident in 1975 involving a pineapple.",
            "Stork margarine is, despite its name, made from budgerigars.",
            "The three-toed sloth, previously thought to be the slowest creature on earth, in fact oscillates at ultra-high frequencies, undetectable to the naked human eye, making it in truth the fastest creature on earth.",
            "Former Prime Minister John Major is made entirely of balsa wood.",
            "Swedish superbabe Ulrika Jonsson has an honorary doctorate in bullfighting from the University of Pamplona.",
            "The Spice Girls have an aggregate IQ of over eight thousand, making them the brainiest per capita pop group in the world.",
            "It is widely known that 'Gorgeous' George Clooney, star of Batman and ER, has two wooden legs, but not so well known that he also has a wooden head.",
            "God's new web-site can be found at http://www.big.G.com/. The site, optimised for Netscape 3 with Shockwave plug-in, features a picture of God on a skate-board, words to his favourite songs, and some cool links.",
            "\"Pamplemousse\", the French word for grapefruit, literally translates into English as \"whore's buttock\".",
            "Actress Doris Day, real name Brian Chedlington, got the inspiration for her stage-name from Boris Bay on the west coast of Scotland.",
            "\"You can lead a horse to water but you can't make him drink\" says the ancient proverb, but new research by top Lebanese scientists has startlingly disproved this theory.",
            "The boy's name Thomas is derived from the Middle English word `Thumlasse', meaning `he who has no thumbs'."
        ]
    },

    {
        "name": "Mr Colin McChesney",
        "bio.1": "Our eleventh guest liar",
        "bio.2": "Mr Colin McChesney",
        "bio.3": "who listed among his hobbies; blue, amber and beige.",
        "lies": [
            "Under an obscure law passed by King Carol Vorderman in the 1800's, all shopkeepers are obliged to sell any item for only one penny on presentation of a stained glass helicopter and the words \"Chewing a stately banjo\".",
            "According to a recent survey, 3 out of 5 candlemakers regularly mistake cinemas for chocolate digestives.",
            "Nightmares can be prevented by covering ones bedclothes with radioactive plutonium at least an hour before bedtime.",
            "The Spanish have no word for \"duck\", due to an ancient legend that states that, if such a word were to be adopted into the language, Abba would reform for a comeback tour.",
            "Hirsute television star David Hasselhoff claims that laying strips of uncooked bacon over your head just before bedtime is an excellent cure for baldness.",
            "Elton John orchestrated the death of Princess Diana.",
            "The NASA probe currently en-route to Mars contains a Werthers Original toffee which fell from the mouth of a technician into the innards of the craft, and could not be removed in time for the launch.",
            "The currency of Brazil is the Kraft Cheese Slice.",
            "All computer mice only have 4,725,245 clicks available for use",
            "American astronaut Neil Armstrong actually made two trips to the moon. He returned in 1975 to retrieve has wallet and car-keys which he had left behind on the previous occasion.",
            "It wasn't an iceberg that sunk the Titanic; in fact, it was just too heavy to float.",
            "The city of Glasgow was so named due to the mysterious disappearance of over 200 transparent drinking vessels in the area during the middle ages.",
            "Screen actress Michelle Pfeiffer was the first woman to wear a hat on a live broadcast of international pro-celebrity potato farming.",
            "Gravity is an illusion caused by millions of microscopically tiny ants which continually attempt to drag you into their subterranean lairs.",
            "Film director Alfred Hitchcock's first words were \"Half a pound of cheese, please\".",
            "Popular television series \"Scooby Doo\" is based on the real-life exploits on a group of American teenagers who, accompanied by their intelligent but cowardly dog, travelled the country solving mysteries during the sixties."
        ]
    }
]