name: update-o-matic

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch: {} 

permissions:
  contents: write  # required to push back to the repo

concurrency:
  group: auto-build-and-push
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # so we can commit & push

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Stage changes under root/
        id: stage
        run: |
          # -A to include deletions/renames inside root/
          git add -A root

          # Detect whether anything changed
          if git diff --staged --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit
        if: steps.stage.outputs.changed == 'true'
        run: |
          git commit -m "chore: automated site rebuild [skip ci]"

      - name: Rebase (just in case) and push
        if: steps.stage.outputs.changed == 'true'
        run: |
          git pull --rebase origin main || true
          git push origin HEAD:main

      - name: Nothing to commit
        if: steps.stage.outputs.changed != 'true'
        run: echo "No changes under root/; skipping commit."
