name: Boring Workflow Name

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run builder
        run: node builder.js

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Branch setup
        run: |
          git branch -D pages
          git switch --orphan pages
          git commit --allow-empty -m 'empty root'

      - name: Stage changes
        run: git add root/*

      - name: Commit changes
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: $(date) automated site rebuild [skip ci]"
            git push --force origin HEAD:pages
          fi
