name: Boring Workflow Name

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

env:
  GENERATOR_DIR: gen
  PAGES_REF: pages

jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ${{ env.GENERATOR_DIR }}
    steps:
      - name: Check out pages content
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PAGES_REF }}

      - name: Check out generator
        uses: actions/checkout@v4
        with:
          path: ${{ env.GENERATOR_DIR }}

      - run: git branch -v
        working-directory: ${{ github.workspace }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.GENERATOR_DIR }}

      - name: Install dependencies
        run: npm ci

      - name: Run builder
        run: node builder.js

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # - name: Branch setup
      #   run: |
      #     git branch -v
      #     git branch -D pages || true
      #     git stash
      #     git switch --orphan pages
      #     git stash pop

      # - name: Stage changes
      #   run: git add root/*

      - name: Commit changes
        working-directory: ${{ github.workspace }}
        run: |
          if git diff --staged --quiet; then
            git status
            ls -alh root || true
            echo "No changes to commit"
          else
            git status
            git commit -m "chore: $(date) automated site rebuild [skip ci]"
            # git push --force origin HEAD:${{ env.PAGES_REF }}
          fi
