name: Boring Workflow Name

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

env:
  GENERATOR_DIR: gen
  PAGES_REF: pages

jobs:
  build_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      do_publish: ${{ steps.commit.outputs.do_publish }}
    steps:
      - name: Check out pages content
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PAGES_REF }}

      - name: Check out generator
        uses: actions/checkout@v4
        with:
          path: ${{ env.GENERATOR_DIR }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./${{ env.GENERATOR_DIR }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ env.GENERATOR_DIR }}
        run: npm ci

      - name: Run builder
        working-directory: ${{ env.GENERATOR_DIR }}
        run: node builder.js

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # - name: Branch setup
      #   run: |
      #     git branch -v
      #     git branch -D pages || true
      #     git stash
      #     git switch --orphan pages
      #     git stash pop

      - name: Stage changes
        run: git add root/*

      - name: Commit changes
        id: commit
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "do_publish=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: $(date) automated site rebuild [skip ci]"
            git push --force origin HEAD:${{ env.PAGES_REF }}
            echo "do_publish=true" >> $GITHUB_OUTPUT
          fi


  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_commit]
    if: fromJson(needs.build_and_commit.outputs.do_publish)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write    # to deploy to Pages
      id-token: write # to verify the deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PAGES_REF }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
