name: Hourly Build (PR + Auto-merge)

on:
  schedule:
    - cron: "0 * * * *"   # hourly, UTC
  workflow_dispatch:

permissions:
  contents: write          # needed to push the PR branch
  pull-requests: write     # needed to create/update PRs

env:
  BASE: main               # change if your default branch is 'master'
  PR_BRANCH: automated/build

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install & build
        run: |
          npm ci
          npm run build

      # Let the action create the branch & PR from the current (clean) workspace
      - name: Create / Update PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          # If you enabled the repo setting (Fix 1), you can omit 'token'.
          # If not, use a PAT (Fix 2):
          # token: ${{ secrets.GH_PAT }}
          base: ${{ env.BASE }}
          branch: ${{ env.PR_BRANCH }}
          title: "Automated hourly build"
          commit-message: "chore(build): automated build"
          labels: automated

      - name: Enable PR auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        env:
          # Use the same token you used above. If Fix 1 is enabled, GITHUB_TOKEN is fine.
          GH_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
