name: rebuild all pages and push to repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # we'll use a token later

      - name: set up
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # use the version your script needs

      - name: install dependencies
        run: npm install

      - name: run build
        run: npm run build

      - name: commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update GitHub Pages content" || echo "No changes to commit"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}" HEAD:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}