name: rebuild all pages and push to repo

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: set up
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependencies
        run: npm install

      - name: run build
        run: npm run build

      - name: commit and push changes
        run: |
          echo hi there
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add .
          git commit -m "chore: update GitHub Pages content" || echo "No changes to commit"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}" HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
