name: rebuild all pages and push to repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # we'll use a token later

      - name: set up
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # use the version your script needs

      - name: install dependencies
        run: npm install

      - name: run build
        run: npm run build

      - name: commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore: update GitHub Pages content" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
